module.exports = {
    CACHE_EXPORT_JOB_LIST: 'CACHE_EXPORT_JOB_LIST',
    CACHE_EXPORT_JOB_SUCCESS_LIST: 'CACHE_EXPORT_JOB_SUCCESS_LIST',
    CACHE_EXPORT_JOB_FAIL_LIST: 'CACHE_EXPORT_JOB_FAIL_LIST',
    COMMON_WAIT_TIME: 5,
}